name: Bug Report
description: Describe a bug in detail.
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: Page URL
      placeholder: https://
    validations:
      required: true
  - type: input
    attributes:
      label: Extension Version
    validations:
      required: true
  - type: input
    attributes:
      label: Browser and Version
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I have reloaded the pages after installing the extension.
          required: true
        - label: I have restarted the browser.
          required: true
