name: Feature Request
description: Describe a feature request in detail.
title: '[Feature Request]: '
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
