on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: pnpm ci
      - run: pnpm tsc
      - run: pnpm format-check
      - run: pnpm playwright install --with-deps
      - run: pnpm playwright test
