on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: pnpm ci
      - run: pnpm exec tsc
      - run: pnpm exec playwright install --with-deps
      - run: pnpm run format-check
      - run: pnpm run test
